### ISSUE TITLE
Cannot install, tried everything. pls help

### ISSUE THREAD

**Issue by fra0furio** [r4victor/afaligner#12]
fra_furio@PCfrafurio:~$ pip install afaligner
Defaulting to user installation because normal site-packages is not writeable
Collecting afaligner
  Using cached afaligner-0.2.0-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: Jinja2>=3.1.2 in ./.local/lib/python3.10/site-packages (from afaligner) (3.1.2)
Collecting aeneas>=1.7.3.0 (from afaligner)
  Using cached aeneas-1.7.3.0.tar.gz (5.5 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: BeautifulSoup4>=4.5.1 in /usr/lib/python3/dist-packages (from aeneas>=1.7.3.0->afaligner) (4.10.0)
Requirement already satisfied: lxml>=3.6.0 in ./.local/lib/python3.10/site-packages (from aeneas>=1.7.3.0->afaligner) (4.9.2)
Requirement already satisfied: numpy>=1.9 in ./.local/lib/python3.10/site-packages (from aeneas>=1.7.3.0->afaligner) (1.24.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib/python3/dist-packages (from Jinja2>=3.1.2->afaligner) (2.0.1)
Building wheels for collected packages: aeneas
  Building wheel for aeneas (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [218 lines of output]
      /tmp/pip-install-jpktaqr7/aeneas_a69c34987af9464494f0056c337dd2f2/setup.py:190: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils import misc_util
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/mfcc.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/synthesizer.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/exacttiming.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/textfile.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/executetask.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/container.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/logger.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/ffmpegwrapper.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/sd.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/hierarchytype.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/wavfile.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/__init__.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/adjustboundaryalgorithm.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/language.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/tree.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/analyzecontainer.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/audiofilemfcc.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/validator.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/job.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/idsortingalgorithm.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/globalfunctions.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/configuration.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/dtw.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/cewsubprocess.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/vad.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/executejob.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/audiofile.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/task.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/plotter.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/ffprobewrapper.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/runtimeconfiguration.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/globalconstants.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/diagnostics.py -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/downloader.py -> build/lib.linux-x86_64-3.10/aeneas
      creating build/lib.linux-x86_64-3.10/aeneas/cdtw
      copying aeneas/cdtw/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/cdtw
      copying aeneas/cdtw/cdtw_setup.py -> build/lib.linux-x86_64-3.10/aeneas/cdtw
      creating build/lib.linux-x86_64-3.10/aeneas/cew
      copying aeneas/cew/cew_setup.py -> build/lib.linux-x86_64-3.10/aeneas/cew
      copying aeneas/cew/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/cew
      creating build/lib.linux-x86_64-3.10/aeneas/cfw
      copying aeneas/cfw/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/cfw
      copying aeneas/cfw/cfw_setup.py -> build/lib.linux-x86_64-3.10/aeneas/cfw
      creating build/lib.linux-x86_64-3.10/aeneas/cmfcc
      copying aeneas/cmfcc/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/cmfcc
      copying aeneas/cmfcc/cmfcc_setup.py -> build/lib.linux-x86_64-3.10/aeneas/cmfcc
      creating build/lib.linux-x86_64-3.10/aeneas/cwave
      copying aeneas/cwave/cwave_setup.py -> build/lib.linux-x86_64-3.10/aeneas/cwave
      copying aeneas/cwave/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/cwave
      creating build/lib.linux-x86_64-3.10/aeneas/extra
      copying aeneas/extra/ctw_espeak.py -> build/lib.linux-x86_64-3.10/aeneas/extra
      copying aeneas/extra/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/extra
      copying aeneas/extra/ctw_speect.py -> build/lib.linux-x86_64-3.10/aeneas/extra
      creating build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/fragmentlist.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfsmil.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfxmllegacy.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfssv.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfjson.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smftextgrid.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/fragment.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfttml.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfsrt.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfeaf.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfgsubtitles.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfrbse.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfvtt.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfgxml.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smftxt.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfaudacity.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/missingparametererror.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/format.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfcsv.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfbase.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfsub.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/headtailformat.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smftsv.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfxml.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      copying aeneas/syncmap/smfgtabular.py -> build/lib.linux-x86_64-3.10/aeneas/syncmap
      creating build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/download.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/plot_waveform.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/read_audio.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/execute_job.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/execute_task.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/extract_mfcc.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/validate.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/run_sd.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/ffprobe_wrapper.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/convert_syncmap.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/hydra.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/ffmpeg_wrapper.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/synthesize_text.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/run_vad.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/abstract_cli_program.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/tools/read_text.py -> build/lib.linux-x86_64-3.10/aeneas/tools
      creating build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      copying aeneas/ttswrappers/espeakttswrapper.py -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      copying aeneas/ttswrappers/macosttswrapper.py -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      copying aeneas/ttswrappers/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      copying aeneas/ttswrappers/espeakngttswrapper.py -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      copying aeneas/ttswrappers/awsttswrapper.py -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      copying aeneas/ttswrappers/basettswrapper.py -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      copying aeneas/ttswrappers/nuancettswrapper.py -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      copying aeneas/ttswrappers/festivalttswrapper.py -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      creating build/lib.linux-x86_64-3.10/aeneas/res
      copying aeneas/res/finetuneas.html -> build/lib.linux-x86_64-3.10/aeneas/res
      copying aeneas/res/LiberationMono-Regular.ttf -> build/lib.linux-x86_64-3.10/aeneas/res
      copying aeneas/res/__init__.py -> build/lib.linux-x86_64-3.10/aeneas/res
      copying aeneas/README.md -> build/lib.linux-x86_64-3.10/aeneas
      copying aeneas/cdtw/cdtw_func.c -> build/lib.linux-x86_64-3.10/aeneas/cdtw
      copying aeneas/cdtw/cdtw_py.c -> build/lib.linux-x86_64-3.10/aeneas/cdtw
      copying aeneas/cdtw/cdtw_driver.c -> build/lib.linux-x86_64-3.10/aeneas/cdtw
      copying aeneas/cdtw/cdtw_func.h -> build/lib.linux-x86_64-3.10/aeneas/cdtw
      copying aeneas/cdtw/README.md -> build/lib.linux-x86_64-3.10/aeneas/cdtw
      copying aeneas/cew/speak_lib.h -> build/lib.linux-x86_64-3.10/aeneas/cew
      copying aeneas/cew/cew_func.h -> build/lib.linux-x86_64-3.10/aeneas/cew
      copying aeneas/cew/README.md -> build/lib.linux-x86_64-3.10/aeneas/cew
      copying aeneas/cmfcc/cmfcc_driver.c -> build/lib.linux-x86_64-3.10/aeneas/cmfcc
      copying aeneas/cmfcc/cmfcc_func.c -> build/lib.linux-x86_64-3.10/aeneas/cmfcc
      copying aeneas/cmfcc/cmfcc_py.c -> build/lib.linux-x86_64-3.10/aeneas/cmfcc
      copying aeneas/cmfcc/cmfcc_func.h -> build/lib.linux-x86_64-3.10/aeneas/cmfcc
      copying aeneas/cmfcc/README.md -> build/lib.linux-x86_64-3.10/aeneas/cmfcc
      copying aeneas/cwave/cwave_func.c -> build/lib.linux-x86_64-3.10/aeneas/cwave
      copying aeneas/cwave/cwave_driver.c -> build/lib.linux-x86_64-3.10/aeneas/cwave
      copying aeneas/cwave/cwave_py.c -> build/lib.linux-x86_64-3.10/aeneas/cwave
      copying aeneas/cwave/cwave_func.h -> build/lib.linux-x86_64-3.10/aeneas/cwave
      copying aeneas/cwave/README.md -> build/lib.linux-x86_64-3.10/aeneas/cwave
      copying aeneas/extra/README.md -> build/lib.linux-x86_64-3.10/aeneas/extra
      creating build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/audio.wav -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/sonnet.vad -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/subtitles.txt -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/job.bad.zip -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/mplain.txt -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/parsed.txt -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/sonnet.zzz -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/unparsed.xhtml -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/page.xhtml -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/audio.mp3 -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/sonnet.json -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/job_no_config.zip -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/config.bad.txt -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/config.bad.xml -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/plain.txt -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/config.txt -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/job.zip -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/sonnet.csv -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/munparsed2.xhtml -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/munparsed.xhtml -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/config.xml -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/res/words.txt -> build/lib.linux-x86_64-3.10/aeneas/tools/res
      copying aeneas/tools/README.md -> build/lib.linux-x86_64-3.10/aeneas/tools
      copying aeneas/ttswrappers/README.md -> build/lib.linux-x86_64-3.10/aeneas/ttswrappers
      running build_ext
      building 'aeneas.cdtw.cdtw' extension
      Warning: Can't read registry to find the necessary compiler setting
      Make sure that Python modules winreg, win32api or win32con are installed.
      INFO: C compiler: x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
      
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/aeneas
      creating build/temp.linux-x86_64-3.10/aeneas/cdtw
      creating build/temp.linux-x86_64-3.10/aeneas/cint
      INFO: compile options: '-I/home/fra_furio/.local/lib/python3.10/site-packages/numpy/core/include -I['/home/fra_furio/.local/lib/python3.10/site-packages/numpy/core/include'] -I/usr/include/python3.10 -c'
      INFO: x86_64-linux-gnu-gcc: aeneas/cdtw/cdtw_func.c
      INFO: x86_64-linux-gnu-gcc: aeneas/cdtw/cdtw_py.c
      INFO: x86_64-linux-gnu-gcc: aeneas/cint/cint.c
      INFO: x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/aeneas/cdtw/cdtw_func.o build/temp.linux-x86_64-3.10/aeneas/cdtw/cdtw_py.o build/temp.linux-x86_64-3.10/aeneas/cint/cint.o -o build/lib.linux-x86_64-3.10/aeneas/cdtw/cdtw.cpython-310-x86_64-linux-gnu.so
      building 'aeneas.cmfcc.cmfcc' extension
      INFO: C compiler: x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
      
      creating build/temp.linux-x86_64-3.10/aeneas/cmfcc
      creating build/temp.linux-x86_64-3.10/aeneas/cwave
      INFO: compile options: '-I/home/fra_furio/.local/lib/python3.10/site-packages/numpy/core/include -I['/home/fra_furio/.local/lib/python3.10/site-packages/numpy/core/include'] -I/usr/include/python3.10 -c'
      INFO: x86_64-linux-gnu-gcc: aeneas/cint/cint.c
      INFO: x86_64-linux-gnu-gcc: aeneas/cmfcc/cmfcc_py.c
      INFO: x86_64-linux-gnu-gcc: aeneas/cmfcc/cmfcc_func.c
      INFO: x86_64-linux-gnu-gcc: aeneas/cwave/cwave_func.c
      aeneas/cmfcc/cmfcc_func.c: In function ‘_precompute_sin_table’:
      aeneas/cmfcc/cmfcc_func.c:83:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]
         83 |     for (k = 1; k < size; ++k) {
            |                   ^
      aeneas/cmfcc/cmfcc_func.c: In function ‘fft’:
      aeneas/cmfcc/cmfcc_func.c:109:31: warning: comparison of integer expressions of different signedness: ‘int’ and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]
        109 |             for (li = lix; li <= m; li += lix) {
            |                               ^~
      INFO: x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/aeneas/cint/cint.o build/temp.linux-x86_64-3.10/aeneas/cmfcc/cmfcc_func.o build/temp.linux-x86_64-3.10/aeneas/cmfcc/cmfcc_py.o build/temp.linux-x86_64-3.10/aeneas/cwave/cwave_func.o -o build/lib.linux-x86_64-3.10/aeneas/cmfcc/cmfcc.cpython-310-x86_64-linux-gnu.so
      building 'aeneas.cew.cew' extension
      INFO: C compiler: x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
      
      creating build/temp.linux-x86_64-3.10/aeneas/cew
      INFO: compile options: '-I['/home/fra_furio/.local/lib/python3.10/site-packages/numpy/core/include'] -I/usr/include/python3.10 -c'
      INFO: x86_64-linux-gnu-gcc: aeneas/cew/cew_func.c
      INFO: x86_64-linux-gnu-gcc: aeneas/cew/cew_py.c
      INFO: x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/aeneas/cew/cew_func.o build/temp.linux-x86_64-3.10/aeneas/cew/cew_py.o -lespeak -o build/lib.linux-x86_64-3.10/aeneas/cew/cew.cpython-310-x86_64-linux-gnu.so
      /usr/bin/ld: cannot find -lespeak: No such file or directory
      collect2: error: ld returned 1 exit status
      error: Command "x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/aeneas/cew/cew_func.o build/temp.linux-x86_64-3.10/aeneas/cew/cew_py.o -lespeak -o build/lib.linux-x86_64-3.10/aeneas/cew/cew.cpython-310-x86_64-linux-gnu.so" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aeneas
  Running setup.py clean for aeneas
Failed to build aeneas
ERROR: Could not build wheels for aeneas, which is required to install pyproject.toml-based projects

**Comment by KevChristoffers** [comment]
Near the bottom of the error message, it says:
`cannot find -lespeak: No such file or directory`
[This issue has that same error message](https://github.com/readbeyond/aeneas/issues/229)
Running `sudo apt-get install libespeak-dev` should fix it.

**Comment by rabomen** [comment]
How about Mac? Can I install libespeak-dev in macOS?
