### ISSUE TITLE
[Request] Forced Alignment for Subtitles

### ISSUE THREAD

**Issue by echoIIImk2** [r4victor/afaligner#13]
Would you please start a new project to create aligned subtitles for movies/TV shows/Pods etc.? 
Subtitles for movies and TV are similar to audiobooks, most of the code should be the same as afaligner. 
The differences are mainly as follows:
1. The aligned subtitles are in srt format, not smil.
2. Afaligner currently handles audiobooks in such a way that the end timestamp of each sentence is the same as the start timestamp of the next sentence, which is not in line with the requirements of subtitles for movies and TV, and needs to accurately identify the end timestamp of each sentence.

In addition, it may be necessary to consider that there may be large intervals without dialogue in the movie and TV.

**Comment by r4victor** [comment]
@echoIIImk2, I'm not into subtitles production, so I'm unlikely to start a project in this space. But I'm curious why you would need a forced aligner for subtitles in the first place. I'd assume if you need to produce English subtitles for the original English audio track, then you can just run speech-to-text and get timestamps automatically. Isn't this how you produce subtitles nowadays?
