### ISSUE TITLE
How to support Mandarin?

### ISSUE THREAD

**Issue by xiuxiu** [r4victor/afaligner#4]
Hi,

I am searching for mandarin forced alignment tool.

Is it possible to add mandarin support? Please help.

Regards
Rock

**Comment by r4victor** [comment]
Hi, @xiuxiu! `afaligner` doesn't provide any support for languages other than English out of the box. However, the only language-specific step in the synchronization process is the text-to-speech synthesis. The text-to-speech synthesis relies on the [aeneas](https://github.com/readbeyond/aeneas) library that invokes a synthesizer (`espeak` by default).  `espeak` [supports Mandarin](https://www.readbeyond.it/aeneas/docs/espeakttswrapper.html#aeneas.ttswrappers.espeakttswrapper.ESPEAKTTSWrapper.CMN), and `aenaes` allows you to specify the language by passing the `TTS_VOICE_CODE` parameter in the runtime configuration.

Update: see the solution in the next post. This doesn't seem to work =>

Now `afaligner` [calls ](https://github.com/r4victor/afaligner/blob/master/afaligner/__init__.py#L167) the synthesizer like this:

```python
synthesizer = Synthesizer(rconf)
...
anchors,_,_ = synthesizer.synthesize(textfile, text_wav_path)
```

Call it like this instead to specify the language:

```python
rconf = RuntimeConfiguration()
rconf.TTS_VOICE_CODE = 'cmn' # mandarin
synthesizer = Synthesizer(rconf)
...
anchors,_,_ = synthesizer.synthesize(textfile, text_wav_path)
```

`afaligner` is not flexible, so you need to modify the source code to enable this. Alternatively, you can use `aeneas` directly. It's also a forced aligner.

I cannot say anything about the quality of alignment of Mandarin texts.

**Comment by r4victor** [comment]
Sorry, I misunderstood the `aeneas` docs. The solutions is different. You need to specify the language of the text. 

Change [this line](https://github.com/r4victor/afaligner/blob/master/afaligner/__init__.py#L162):

```python
textfile.set_language(Language.ENG)
```

to this:


```python
textfile.set_language(Language.CMN)
```

I checked it produces something that is not English, most likely Mandarin.
