### ISSUE TITLE
Sync returning with 'killed'

### ISSUE THREAD

**Issue by WoxWik** [r4victor/afaligner#9]
When I run sync, a couple of wav files get created, and then the process displays 'Killed'. This happens in both docker and on baremetal linux. I've tried with two books so far.

I've pinpointed it to this function call - but not sure why exactly things are going wrong.
https://github.com/r4victor/afaligner/blob/92900f5968a8cd3c895be81dcf180deee9b8c3c1/src/afaligner/c_dtwbd_wrapper.py#L36

**Comment by r4victor** [comment]
@WoxWik , most probably out of memory. Answered here: https://github.com/r4victor/afaligner/issues/2#issuecomment-1465154315
